import type { GadgetManifest, GadgetType } from './types';

export const GADGET_REGISTRY: Record<GadgetType, GadgetManifest> = {
  youtube: {
    type: 'youtube',
    kind: 'embed',
    category: 'integration',
    availability: 'trusted',
    label: 'YouTube',
    icon: 'video',
    accent: '#ef4444',
    needsUrl: true,
    placeholder: 'YouTube URL...',
    description: 'Embed a YouTube player.',
    urlHint: 'Paste a youtube.com/watch or youtu.be link.',
  },
  code: {
    type: 'code',
    kind: 'native',
    category: 'productivity',
    availability: 'built-in',
    label: 'Code',
    icon: 'code',
    accent: '#6366f1',
    description: 'Insert a code block.',
  },
  poll: {
    type: 'poll',
    kind: 'native',
    category: 'collaboration',
    availability: 'built-in',
    label: 'Poll',
    icon: 'vote',
    accent: '#0d9488',
    description: 'Add a native poll gadget.',
  },
  latex: {
    type: 'latex',
    kind: 'native',
    category: 'productivity',
    availability: 'built-in',
    label: 'LaTeX',
    icon: 'sigma',
    accent: '#8b5cf6',
    description: 'Insert a math block starter.',
  },
  iframe: {
    type: 'iframe',
    kind: 'embed',
    category: 'integration',
    availability: 'trusted',
    label: 'iFrame',
    icon: 'external-link',
    accent: '#64748b',
    needsUrl: true,
    placeholder: 'Embed URL...',
    description: 'Embed a trusted external frame.',
    urlHint: 'Use a full http or https URL.',
  },
  spreadsheet: {
    type: 'spreadsheet',
    kind: 'embed',
    category: 'visualization',
    availability: 'trusted',
    label: 'Sheet',
    icon: 'table',
    accent: '#22c55e',
    needsUrl: true,
    placeholder: 'Google Sheets URL...',
    description: 'Embed a spreadsheet URL.',
    urlHint: 'Paste a docs.google.com/spreadsheets link.',
  },
  image: {
    type: 'image',
    kind: 'native',
    category: 'visualization',
    availability: 'built-in',
    label: 'Image',
    icon: 'image',
    accent: '#2563eb',
    needsUrl: true,
    placeholder: 'Image URL...',
    description: 'Embed a remote image.',
    urlHint: 'Use a full http or https image URL.',
  },
  kanbanApp: {
    type: 'kanbanApp',
    appId: 'kanban-board',
    kind: 'app',
    category: 'productivity',
    availability: 'preview',
    label: 'Kanban',
    icon: 'columns',
    accent: '#0f766e',
    description: 'Mount a sandboxed kanban preview app inside the topic.',
  },
  calendarApp: {
    type: 'calendarApp',
    appId: 'calendar-planner',
    kind: 'app',
    category: 'productivity',
    availability: 'preview',
    label: 'Planner',
    icon: 'calendar',
    accent: '#2563eb',
    description: 'Mount a sandboxed planning preview app inside the topic.',
  },
  focusApp: {
    type: 'focusApp',
    appId: 'focus-timer',
    kind: 'app',
    category: 'productivity',
    availability: 'preview',
    label: 'Focus',
    icon: 'timer',
    accent: '#7c3aed',
    description: 'Mount a sandboxed focus timer preview app inside the topic.',
  },
};

export const AVAILABLE_GADGETS = Object.values(GADGET_REGISTRY);

export function getGadgetManifest(type?: GadgetType | null): GadgetManifest {
  return GADGET_REGISTRY[type || 'iframe'] || GADGET_REGISTRY.iframe;
}
