#!/usr/bin/env python3
import pathlib


PATH = pathlib.Path("/mnt/g/My Drive/Tana/tana-claude-workflow.md")


def replace_once(text, old, new):
    if old in text:
        return text.replace(old, new)
    if new in text:
        return text
    raise RuntimeError(f"Expected snippet not found in {PATH}: {old[:120]!r}")


def main():
    text = PATH.read_text()

    text = replace_once(
        text,
        "- discussion: Ux8stlKm4NM_\n- annotation-run: 66SFmrfgsLQv\n",
        "- discussion: Ux8stlKm4NM_\n- reply: CRnHZin1KPtE (fields: Author/Knni2KFxspb6 instance #person, In reply to/W1kkUBa9yFw- plain text, Read by/ImjX9CVg4tmr multi instance #person)\n- annotation-run: 66SFmrfgsLQv\n",
    )
    text = replace_once(
        text,
        "- data-source: tN5RCt6Cj69X\n",
        "- data-source: tN5RCt6Cj69X\n- taxonomy: 1qGdou2zICCW\n",
    )
    text = replace_once(
        text,
        "- Deterrence: lWo_QlgXCBb0\n- NOTE: #Russia was TRASHED - RuBase protocol covers everything Russia-related\n",
        "- Deterrence: lWo_QlgXCBb0\n- Grey Zone: TDNZi-bd199w\n- Nuclear: HzECN_6W_ILu\n- Influence Operations: HiDhHaq97V8M\n- Drones & UAVs: zAWPvdCdD1No\n- Military Regeneration: gjtRl-Ho8JkV\n- Sanctions: Il2WP_ZDaTJ0\n- Resilience: uLzKd_hmh7No\n- Defense Economics: uH1hYRE9ukHk\n- MENA: 2tXjcGHahHyK\n- NOTE: #Russia was TRASHED - RuBase protocol covers everything Russia-related\n",
    )
    text = replace_once(
        text,
        "- OffBase: bwy8Ya7Cz85M\n",
        "- OffBase: bwy8Ya7Cz85M\n- PolicyBase: I2S3lqOu88vN\n- TimeBase: iFrNQqho-ePl\n- FutureBase: eaSdkE6dq44F\n- MICBase: 9YP9ZYHuotPT\n",
    )
    text = replace_once(
        text,
        "- Corpus Building: K_prgKBGMppC\n",
        "- Corpus Building: K_prgKBGMppC\n- Sentiment Analysis: 4A8I6Cfj08P7\n- Foresight: XSVaHL3CTmxb\n- Wargaming: Jq36YiTzsJOl\n- RAG: oL5p8If4UdoX\n- Classification: WB9sAsckfrIp\n- Semantic Search: HSoqvC_X8eVP\n- Benchmarking: YBPRsmB6CAI0\n- Manual Coding: ugYoDCdCJvE4\n- Text Mining: rK319zicdT1W\n- Network Analysis: b8Kq04jo0sjC\n- Embedding: 7j7mi7QfORDa\n- Ontology Development: KV2WNCMAZuCd\n",
    )
    text = replace_once(
        text,
        "- Metabase: fTgmRfyyjYqG\n",
        "- Metabase: fTgmRfyyjYqG\n- PostgreSQL: 4nkYcjHJDJYI\n- Claude: 39bzN4PyAMqn\n- spaCy: ChPEWN4iC7jM\n- Docker: U_poqhYAtFeH\n- Google Colab: 88jijB7frK6F\n- CiteSpace: xLNbwLUMEze1\n",
    )
    text = replace_once(
        text,
        "- Google Scholar: GJMu0UO0ENGB\n",
        "- Google Scholar: GJMu0UO0ENGB\n- ACLED: JdJoEBIXGWHB\n- ICEWS: -17nSABA-tGU\n- SIPRI: wo82gpdgrkEr\n- VK: DVnqnS50e5RQ\n- WDI: 2aU7DIFuWgSe\n- Military Balance: yhkRicaFGv3z\n- Milbloggers: vUlWNPktDMk0\n",
    )
    text = replace_once(
        text,
        "### Trashed Duplicate/Empty Tags\n- person (empty dup): u4XP3ITtgx8T\n- study (empty dup): GaY62Ug8mNoU\n- Rizzoma-Tana (empty dup): 7Gv-YL5FhnHT\n- Corpus (empty): hCLGGuL3_Nlj\n- Transparent (empty): EWolFA29VjZD\n\n### Key Nodes\n",
        "### Trashed Duplicate/Empty/Rogue Tags\n- person (empty dup): u4XP3ITtgx8T\n- study (empty dup): GaY62Ug8mNoU\n- Rizzoma-Tana (empty dup): 7Gv-YL5FhnHT\n- Corpus (empty): hCLGGuL3_Nlj\n- Transparent (empty): EWolFA29VjZD\n- CLAS (rogue, auto-created by import_tana_paste): UhMGWxBoUEzE, Mye6tjiBwvEe\n- Transparent (rogue, auto-created by import_tana_paste): 6iQlauwyhmiq\n- person (rogue, auto-created by import_tana_paste): XG6DFjk73t30\n\n### CRITICAL: import_tana_paste Tag Handling\n- import_tana_paste CANNOT resolve multi-word tag names (e.g. `#CLAS RuBase` → creates `#CLAS` + `#RuBase`)\n- It also creates NEW tag definitions instead of matching existing ones\n- ALWAYS use the `tag` tool with explicit tag IDs AFTER importing content\n- NEVER put `#TagName` in Tana Paste content — import plain text, then tag separately\n- After any import, AUDIT the node's tags to verify no rogue tags were created\n- Tag audit (2026-02-24): 92 legitimate tags (53 original + 39 new), 0 rogue — all clean\n\n### Key Nodes\n",
    )
    text = replace_once(
        text,
        "- Study: o7E-2Vu92dxf | Format: rE6FsnK_TBd- | Status: 97M_gbtNN2S0 | Link: xaQ48QUKeowp | Generated by: MUJwRwDzb2pW | Created by: iVa6Q--Yx6q4\n",
        "- Study: o7E-2Vu92dxf | Format: rE6FsnK_TBd- | Status: 97M_gbtNN2S0 | Link: xaQ48QUKeowp | Generated by: MUJwRwDzb2pW | Created by: iVa6Q--Yx6q4 | Rizzoma topic: P_mJqZuqNzAg\n",
    )
    text = replace_once(
        text,
        "### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Generated by: BaewUwERUcWs\n- Generated by opts: Claude(I_e177ygtAEE), Codex(Fn38sEgtZmde), Gemini(GRi58kV6LLaZ), Human(1gWeePPtLrJS), Mixed(KtEGVvl8ox62)\n\n### Field IDs (annotation-run)\n- Study: kcPMfpSND9sd | Model: yFf_i1XKtK2D | Batch size: 228IWilB9_Ww | Taxonomy category: a4fklp1Mxizl | Script link: OEGs5Ph4lyTx\n",
        "### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Generated by: BaewUwERUcWs | Read by: nB79F1NNg4pn (multi, instance #person) | Rizzoma date: 40vNbX5qVJwL\n- Generated by opts: Claude(I_e177ygtAEE), Codex(Fn38sEgtZmde), Gemini(GRi58kV6LLaZ), Human(1gWeePPtLrJS), Mixed(KtEGVvl8ox62)\n\n### Field IDs (annotation-run)\n- Study: kcPMfpSND9sd | Model: yFf_i1XKtK2D | Batch size: 228IWilB9_Ww | Taxonomy category: a4fklp1Mxizl | Script link: OEGs5Ph4lyTx | Created by: sxwe-F6paDNj\n",
    )
    text = replace_once(
        text,
        "### Field IDs (person - ZnwpjWNxNdpj, main workspace)\n- Email: CKFY8AAcQtzY | Zotero: uT7Zm1jlv0uB | Organization: 7ARrAzXTXtAB | LinkedIn: NWB1JyCfpoXe | Phone: jrxaLLetFUg5\n",
        "### Field IDs (person - ZnwpjWNxNdpj, main workspace)\n- First name: xBaVoPZBnf2a | Last name: yD4SnHPDstSp\n- Email: CKFY8AAcQtzY | Zotero: uT7Zm1jlv0uB | Organization: 7ARrAzXTXtAB | LinkedIn: NWB1JyCfpoXe | Phone: jrxaLLetFUg5\n",
    )
    text = replace_once(
        text,
        "### People Search Views & Nodes\n- People node: cRFVNE0ats46\n",
        "### HCSS Sidebar Containers\n- Projects: Hk_AFOqyBcEz\n- Protocols: ZGgUpTYp_lPq\n- Methods: MTrKJf1Wg_sO\n- Areas: B_YuU3gXvyKr\n- Data Sources: _DdLLoUrapas\n- Tools: CuL5gjBxNc2o\n- People: zeMD3Fu_Pv7q (7 active members + All People)\n\n### \"All [Category]\" Content Nodes (browsable lists in sidebar)\nThese are regular CONTENT nodes positioned in sidebar containers, containing `[[^nodeId]]` refs\nto actual tagged items. They provide a curated, browsable, alphabetically sorted list.\n\n**Why needed**: Tag definition nodes (supertags) do NOT display content children in the UI —\nthey show the tag schema + \"Build a home for #Tag\" prompt. Adding `[[^nodeId]]` refs as children\nof a tag definition stores them but they're INVISIBLE. A regular content node displays refs correctly.\n\n**Pattern** (reuse for ALL sidebar categories):\n1. `import_tana_paste` — create \"All [Category]\" node under the sidebar container\n2. `import_tana_paste` — add `[[^nodeId]]` refs (one per line, `- [[^id]]`) as children, alphabetically\n3. `move_node` — position after the corresponding tag definition: `{position: 'after', referenceNodeId: tagDefId}`\n4. Do NOT add refs to tag definition nodes — they won't render\n\n**Existing \"All\" nodes**:\n- All People: l4Q-Dk2OIiGG (under People/zeMD3Fu_Pv7q, 39 people alphabetically)\n  - Old search node cRFVNE0ats46 TRASHED — live search nodes can't be reordered via API\n- All Taxonomies: z3iHqJ7ZK2Zk (under Methods/MTrKJf1Wg_sO, after #Taxonomy tag, 29 outputs alphabetically)\n\n**TODO — create \"All\" nodes for other categories when content exists**:\n- Each method with curated outputs/items (e.g. All NLP, All Corpus Annotation)\n- Each protocol with curated items (e.g. All RuBase, All StratBase)\n- Each area with curated items (e.g. All Ukraine, All Deterrence)\n- Each tool with curated items (e.g. All Tana, All PostgreSQL)\n- Each data source with curated items (e.g. All Integrum, All GDELT)\n- Only create when there's a meaningful list to populate — don't create empty \"All\" nodes\n\n### People Search Views & Nodes\n- People node: zeMD3Fu_Pv7q (was cRFVNE0ats46 search node, replaced)\n",
    )
    text = replace_once(
        text,
        "- Hryhorii: hMTNx10XugEk | Liliia: 1IbTT5gtHvpG | Stephan: X6yCff_d87Wn | Yar Batoh: ipj55K5BwlYh (Past, deceased 2024)\n",
        "- Stephan De Spiegeleire (SDS): X6yCff_d87Wn | Hryhorii Pavlenko (HP): hMTNx10XugEk | Liliia Hudziuk (LH): 1IbTT5gtHvpG | Yar Batoh: ipj55K5BwlYh (Past, deceased 2024)\n",
    )
    text = replace_once(
        text,
        "### Field IDs (task - HCSS workspace, X_vT1GSytHJy) ← USE THIS\n- Status: VCo-GXRip7zs (options)\n- Assignee: 8sQ4hBaQR5IS (instance of #person, multi-value)\n- Due date: TMn-2LAmfF7c\n- Deliverable: rWrnJmkQtZC9 (instance of #deliverable)\n- Rizzoma topic: LBk-z3_L5mZO (instance of #rizzoma-topic)\n- Status opts: To-Do(OctarrhyeoLS), Doing(aloZ9jKRpOXI), Done(flvTePcrabaj), Waiting for(RWxP7Gh7HSXa), Stalled(MEBqUv5Bt5RY), Needs Review(BdbfMXiGsS-_)\n",
        "### Field IDs (task - HCSS workspace, X_vT1GSytHJy) ← USE THIS\n- Status: VCo-GXRip7zs (options)\n- Assignee: 8sQ4hBaQR5IS (instance of #person, multi-value)\n- Due date: TMn-2LAmfF7c\n- Deliverable: rWrnJmkQtZC9 (instance of #deliverable)\n- Rizzoma topic: LBk-z3_L5mZO (instance of #rizzoma-topic)\n- Created by: MCkSxKHFv7st (instance of #person)\n- Generated by: dG5OQzKA6eYV (options: Claude/AUjPowsHSBEC, Codex/S1L6t4Bq8A_Z, Gemini/hCcjwptnMN5v, Human/v0TVDCg8FOeq, Mixed/q4Xdq294wZlw)\n- Rizzoma date: Xgt4EE3vIyQK\n- Status opts: To-Do(OctarrhyeoLS), Doing(aloZ9jKRpOXI), Done(flvTePcrabaj), Waiting for(RWxP7Gh7HSXa), Stalled(MEBqUv5Bt5RY), Needs Review(BdbfMXiGsS-_)\n",
    )
    text = replace_once(
        text,
        "## Daily Notes Pattern\n- ALWAYS post work to today's daily note (get_or_create_calendar_node, workspace HCSS, granularity: day)\n- Each item is a top-level child of the day node (NOT nested inside a wrapper)\n- Tag every item: #task for actions, #discussion for conversations/notes, #meeting for meetings\n- Provenance rule:\n  - `Created by` is for the HUMAN person node only.\n  - Do NOT put the LLM/model in `Created by`.\n  - For replies, use `Author` as the human provenance field.\n  - For daily-note node types that support it, ALSO set `Generated by` to the relevant LLM or provenance mode.\n- ALWAYS apply project/study as VISIBLE SUPERTAGS using proper supertag DEFINITIONS (created via create_tag)\n  - Project tag is PRIMARY (always apply): e.g. #CLAS RuBase (8kRj7CI8rv4H)\n  - Study tag is SECONDARY (only if item is study-specific): e.g. #Transparent Battlefield (QD176nBX1YuQ)\n  - e.g. project-level: \"Fix scrapers #task #CLAS RuBase\"\n  - e.g. study-specific: \"Seed TB research questions #task #CLAS RuBase #Transparent Battlefield\"\n  - NEVER use node instances as tags (they don't render as visible chips in Tana UI)\n- For NEW tasks: use HCSS #task (X_vT1GSytHJy) with fields Status/Assignee/Due date/Deliverable/Rizzoma topic\n- Legacy items from Tana Paste imports have main workspace #task (BE4sP3grlp6R) - don't change these\n- Also set the Study field (es7J4At7t9qg on legacy #task, VBdsrqPcgXHS on #discussion) for search/filtering\n- When posting `#task`, `#discussion`, `#meeting`, or `#output`, set BOTH the human provenance field (`Created by`) and `Generated by`.\n- When posting `#reply`, set `Author` for the human person; there is no `Generated by` field there yet.\n- When posting `#annotation-run`, set `Created by`; add `Generated by` only if the schema gains it later.\n- Mark tasks with checkboxes: [ ] for open, [x] for done\n- Set Status field on tasks (To-Do, Doing, Done)\n- ONE daily note entry per logical batch of work, not separate sub-steps\n- The dashboard searches surface items automatically based on tags + field references\n",
        "## Daily Notes Pattern\n- TWO workspaces, strict separation:\n  - **HCSS** (y_Y6-gpbXQZD): ALL HCSS project work — research, deliverables, team tasks, meetings\n  - **Perso** (e1ZHPKpOXl): personal tasks ONLY — goes here and NOWHERE else\n- Post to the correct workspace's daily note (get_or_create_calendar_node, granularity: day)\n- Each item is a top-level child of the day node (NOT nested inside a wrapper)\n- Tag every item: #task for actions, #discussion for conversations/notes, #meeting for meetings\n- Provenance rule:\n  - `Created by` is for the HUMAN person node only.\n  - Do NOT put the LLM/model in `Created by`.\n  - For replies, use `Author` as the human provenance field.\n  - For daily-note `#task`, `#discussion`, `#meeting`, and `#output`, ALSO set `Generated by`.\n- ALWAYS apply ALL relevant VISIBLE SUPERTAGS — this is NON-NEGOTIABLE:\n  1. **Type tag** (always): #task / #discussion / #meeting\n  2. **Project tag** (always): e.g. #CLAS RuBase (8kRj7CI8rv4H), #Rizzoma-Tana Transition (fi4O0gkWPRwm)\n  3. **Study tag** (if study-specific): e.g. #Transparent Battlefield (QD176nBX1YuQ)\n  4. **Tool tags** (if relevant): e.g. #Tana, #PostgreSQL, #Claude, #Zotero — tag with EVERY tool used\n  5. **Method tags** (if relevant): e.g. #NLP, #Corpus Annotation, #Classification\n  6. **Protocol tags** (if relevant): e.g. #RuBase, #StratBase\n  7. **Area tags** (if relevant): e.g. #Ukraine, #China, #Defense & Security\n  - NEVER use node instances as tags (they don't render as visible chips in Tana UI)\n- NEVER put `#TagName` in `import_tana_paste` content — it creates rogue duplicate tags\n- Standard posting flow (5 steps):\n  1. `import_tana_paste` — plain text only, NO `#tag` references in content\n  2. `tag` — add ALL supertags in one explicit tag-IDs call\n  3. `edit_node` — add `[SDS]` / `[HP]` / `[LH]` suffix if not already in the imported text\n  4. `set_field_content` — set human provenance, Study, and other plain/instance fields\n  5. `set_field_option` — set Status and other option fields\n- After ANY import: verify node tags via `read_node` or `get_children` — catch rogue tags immediately\n- ALWAYS add author suffix to node names: `[SDS]`, `[HP]`, `[LH]` etc. at the END of the name\n  - Default: [SDS] for posts on behalf of Stephan\n  - Initials: SDS=Stephan De Spiegeleire, HP=Hryhorii Pavlenko, LH=Liliia Hudziuk\n- ALWAYS set the human provenance field after posting: use `set_field_content` with the person node ID\n  - Default author: SDS (X6yCff_d87Wn) unless posting on behalf of someone else\n  - Task: MCkSxKHFv7st | Discussion: RxLacB6oylwm | Annotation-run: sxwe-F6paDNj | Meeting: WPVL2EKgjYjz | Output: iVa6Q--Yx6q4 | Reply Author: Knni2KFxspb6\n- `Created by` is for the human author/person only, never the LLM/model.\n- Daily-note `#task`, `#discussion`, `#meeting`, and `#output` should ALSO set `Generated by`.\n  - Task: dG5OQzKA6eYV | Discussion: BaewUwERUcWs | Meeting: DL0Fe4k1v_bQ | Output: MUJwRwDzb2pW\n- Replies use `Author` instead of `Created by` and currently have no `Generated by` field.\n- `#annotation-run` currently uses only `Created by` unless a `Generated by` field is added later.\n- For NEW tasks: use HCSS #task (X_vT1GSytHJy) with fields Status/Assignee/Due date/Deliverable/Rizzoma topic\n- Legacy items from Tana Paste imports have main workspace #task (BE4sP3grlp6R) - don't change these\n- Also set the Study field (es7J4At7t9qg on legacy #task, VBdsrqPcgXHS on #discussion) for search/filtering\n- Mark tasks with checkboxes: [ ] for open, [x] for done\n- Set Status field on tasks (To-Do, Doing, Done)\n- ONE daily note entry per logical batch of work, not separate sub-steps\n- The dashboard searches surface items automatically based on tags + field references\n- REPLIES to discussions: add child node with #reply tag, set Author field (person ID) and \"In reply to\" field (context text)\n  - Pattern: import_tana_paste child → tag with #reply → set_field_content for Author + In reply to\n",
    )

    PATH.write_text(text)
    print(f"updated {PATH}")


if __name__ == "__main__":
    main()
