#!/usr/bin/env python3
import pathlib


PATH = pathlib.Path("/mnt/c/Apps/Tana/docs/tana-claude-workflow.md")


def replace_once(text, old, new):
    if old in text:
        return text.replace(old, new)
    if new in text:
        return text
    raise RuntimeError(f"Expected snippet not found in {PATH}: {old[:80]!r}")


def main():
    text = PATH.read_text()
    text = replace_once(
        text,
        "# Tana + Claude Code Workflow Patterns\n\n## Overview\n",
        "# Tana + Claude Code Workflow Patterns\n\n> Local mirror: use `/mnt/g/My Drive/Tana/tana-claude-workflow.md` as canonical when available.\n> This copy should be kept aligned with the canonical file but is secondary.\n\n## Overview\n",
    )
    text = replace_once(
        text,
        "### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Read by: nB79F1NNg4pn (multi, instance #person) | Rizzoma date: 40vNbX5qVJwL\n",
        "### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz | Generated by: DL0Fe4k1v_bQ\n- Generated by opts: Claude(vE1SjO_A6cUG), Codex(ashbc8EMmP8i), Gemini(0Ob6wrWQgIMC), Human(7RTLGhAPoHi7), Mixed(UejRJCmsiM1T)\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Generated by: BaewUwERUcWs | Read by: nB79F1NNg4pn (multi, instance #person) | Rizzoma date: 40vNbX5qVJwL\n- Generated by opts: Claude(I_e177ygtAEE), Codex(Fn38sEgtZmde), Gemini(GRi58kV6LLaZ), Human(1gWeePPtLrJS), Mixed(KtEGVvl8ox62)\n",
    )
    PATH.write_text(text)
    print(f"updated {PATH}")


if __name__ == "__main__":
    main()
