#!/usr/bin/env python3
import pathlib


REPLACEMENTS = {
    "/mnt/g/My Drive/Tana/tana-claude-workflow.md": [
        (
            "### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4\n",
            "### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz | Generated by: DL0Fe4k1v_bQ\n- Generated by opts: Claude(vE1SjO_A6cUG), Codex(ashbc8EMmP8i), Gemini(0Ob6wrWQgIMC), Human(7RTLGhAPoHi7), Mixed(UejRJCmsiM1T)\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Generated by: BaewUwERUcWs\n- Generated by opts: Claude(I_e177ygtAEE), Codex(Fn38sEgtZmde), Gemini(GRi58kV6LLaZ), Human(1gWeePPtLrJS), Mixed(KtEGVvl8ox62)\n",
        ),
        (
            "- Provenance rule:\n  - `Created by` is for the HUMAN person node only.\n  - Do NOT put the LLM/model in `Created by`.\n  - For replies, use `Author` as the human provenance field.\n  - If a `Generated by` field exists on the node type, use that field for `Claude` / `Gemini` / `Human` / `Mixed`.\n",
            "- Provenance rule:\n  - `Created by` is for the HUMAN person node only.\n  - Do NOT put the LLM/model in `Created by`.\n  - For replies, use `Author` as the human provenance field.\n  - For daily-note node types that support it, ALSO set `Generated by` to the relevant LLM or provenance mode.\n",
        ),
        (
            "- When posting nodes that support `Created by`, set it to the relevant person node (e.g. SDS / HP / LH).\n- When posting `#output` nodes, set BOTH `Created by` (person) and `Generated by` (model/human provenance).\n- When posting `#meeting` nodes, set `Created by` to the relevant person node.\n",
            "- When posting `#task`, `#discussion`, `#meeting`, or `#output`, set BOTH the human provenance field (`Created by`) and `Generated by`.\n- When posting `#reply`, set `Author` for the human person; there is no `Generated by` field there yet.\n- When posting `#annotation-run`, set `Created by`; add `Generated by` only if the schema gains it later.\n",
        ),
    ],
    "/mnt/c/Apps/Tana/docs/MEMORY.md": [
        (
            '- Always set "Created by" field after posting (set_field_content with PERSON node ID only)\n  - SDS: X6yCff_d87Wn | HP: hMTNx10XugEk | LH: 1IbTT5gtHvpG\n  - Field IDs: task=MCkSxKHFv7st, discussion=RxLacB6oylwm, annotation-run=sxwe-F6paDNj, meeting=WPVL2EKgjYjz, output=iVa6Q--Yx6q4\n- `Created by` is for the human author/person only, never the LLM/model.\n- Replies use `Author` instead of `Created by`.\n- If the node type has a `Generated by` field, use that for provenance such as `Claude`, `Gemini`, `Human`, or `Mixed`.\n',
            '- Always set the human provenance field after posting (person node ID only)\n  - SDS: X6yCff_d87Wn | HP: hMTNx10XugEk | LH: 1IbTT5gtHvpG\n  - Human field IDs: task=MCkSxKHFv7st, discussion=RxLacB6oylwm, annotation-run=sxwe-F6paDNj, meeting=WPVL2EKgjYjz, output=iVa6Q--Yx6q4, reply-author=Knni2KFxspb6\n- `Created by` is for the human author/person only, never the LLM/model.\n- Daily-note `#task`, `#discussion`, `#meeting`, and `#output` should ALSO set `Generated by`.\n  - Generated by field IDs: task=dG5OQzKA6eYV, discussion=BaewUwERUcWs, meeting=DL0Fe4k1v_bQ, output=MUJwRwDzb2pW\n- Replies use `Author` instead of `Created by` and currently have no `Generated by` field.\n- `#annotation-run` currently uses only `Created by` unless a `Generated by` field is added later.\n',
        ),
    ],
    "/mnt/c/Apps/Tana/MEMORY.md": [
        (
            '- Always set "Created by" field after posting (set_field_content with PERSON node ID only)\n  - SDS: X6yCff_d87Wn | HP: hMTNx10XugEk | LH: 1IbTT5gtHvpG\n  - Field IDs: task=MCkSxKHFv7st, discussion=RxLacB6oylwm, annotation-run=sxwe-F6paDNj, meeting=WPVL2EKgjYjz, output=iVa6Q--Yx6q4\n- `Created by` is for the human author/person only, never the LLM/model.\n- Replies use `Author` instead of `Created by`.\n- If the node type has a `Generated by` field, use that for provenance such as `Claude`, `Gemini`, `Human`, or `Mixed`.\n',
            '- Always set the human provenance field after posting (person node ID only)\n  - SDS: X6yCff_d87Wn | HP: hMTNx10XugEk | LH: 1IbTT5gtHvpG\n  - Human field IDs: task=MCkSxKHFv7st, discussion=RxLacB6oylwm, annotation-run=sxwe-F6paDNj, meeting=WPVL2EKgjYjz, output=iVa6Q--Yx6q4, reply-author=Knni2KFxspb6\n- `Created by` is for the human author/person only, never the LLM/model.\n- Daily-note `#task`, `#discussion`, `#meeting`, and `#output` should ALSO set `Generated by`.\n  - Generated by field IDs: task=dG5OQzKA6eYV, discussion=BaewUwERUcWs, meeting=DL0Fe4k1v_bQ, output=MUJwRwDzb2pW\n- Replies use `Author` instead of `Created by` and currently have no `Generated by` field.\n- `#annotation-run` currently uses only `Created by` unless a `Generated by` field is added later.\n',
        ),
    ],
    "/mnt/c/Apps/Tana/tana-claude-workflow.md": [
        (
            "# Tana + Claude Code Workflow Patterns\n\n## Overview\n",
            "# Tana + Claude Code Workflow Patterns\n\n> DEPRECATED MIRROR: This file is kept only as an older local copy.\n> Use `/mnt/g/My Drive/Tana/tana-claude-workflow.md` as the canonical workflow doc.\n> Treat `/mnt/c/Apps/Tana/docs/tana-claude-workflow.md` as the fresher local mirror if the Google Drive copy is unavailable.\n\n## Overview\n",
        ),
        (
            "### Field IDs (output - was \"deliverable\")\n- Study: o7E-2Vu92dxf | Format: rE6FsnK_TBd- | Status: 97M_gbtNN2S0 | Link: xaQ48QUKeowp | Generated by: MUJwRwDzb2pW\n- Format opts: 2-pager(t-_Yb9TVBqnU), 20-pager(NYGLnt0-cLuO), Full report(4L5A48QsEO-U), 5-slides(RyiAwK-rgG8C), 20-slides(l17pSQzntK73), Podcast(w5qSyaRcp2mg), Video(ZTVhogQYWPmv), HTML(_3s6Jt7eM0bJ)\n- Status opts: Not started(MVi0hN2KzBLg), Draft(jhj2P0-iYEOY), Review(KkjC2yXPoYZh), Final(crZ3uo18Ju76)\n- Generated by opts: Claude(fZxJ8a75LGGm), Gemini(KVEjkSFsCVW8), Human(XMgbEumYjaN9), Mixed(2qm1NzOJAbuy)\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm\n",
            "### Field IDs (output - was \"deliverable\")\n- Study: o7E-2Vu92dxf | Format: rE6FsnK_TBd- | Status: 97M_gbtNN2S0 | Link: xaQ48QUKeowp | Generated by: MUJwRwDzb2pW | Created by: iVa6Q--Yx6q4\n- Format opts: 2-pager(t-_Yb9TVBqnU), 20-pager(NYGLnt0-cLuO), Full report(4L5A48QsEO-U), 5-slides(RyiAwK-rgG8C), 20-slides(l17pSQzntK73), Podcast(w5qSyaRcp2mg), Video(ZTVhogQYWPmv), HTML(_3s6Jt7eM0bJ)\n- Status opts: Not started(MVi0hN2KzBLg), Draft(jhj2P0-iYEOY), Review(KkjC2yXPoYZh), Final(crZ3uo18Ju76)\n- Generated by opts: Claude(fZxJ8a75LGGm), Gemini(KVEjkSFsCVW8), Human(XMgbEumYjaN9), Mixed(2qm1NzOJAbuy)\n\n### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz | Generated by: DL0Fe4k1v_bQ\n- Generated by opts: Claude(vE1SjO_A6cUG), Codex(ashbc8EMmP8i), Gemini(0Ob6wrWQgIMC), Human(7RTLGhAPoHi7), Mixed(UejRJCmsiM1T)\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Generated by: BaewUwERUcWs\n- Generated by opts: Claude(I_e177ygtAEE), Codex(Fn38sEgtZmde), Gemini(GRi58kV6LLaZ), Human(1gWeePPtLrJS), Mixed(KtEGVvl8ox62)\n",
        ),
        (
            "- Created by: MCkSxKHFv7st (instance of #person)\n",
            "- Created by: MCkSxKHFv7st (instance of #person)\n- Generated by: dG5OQzKA6eYV (options: Claude/AUjPowsHSBEC, Codex/S1L6t4Bq8A_Z, Gemini/hCcjwptnMN5v, Human/v0TVDCg8FOeq, Mixed/q4Xdq294wZlw)\n",
        ),
        (
            "## Daily Notes Pattern\n- ALWAYS post work to today's daily note (get_or_create_calendar_node, workspace HCSS, granularity: day)\n- Each item is a top-level child of the day node (NOT nested inside a wrapper)\n- Tag every item: #task for actions, #discussion for conversations/notes, #meeting for meetings\n- Provenance rule:\n  - `Created by` is for the HUMAN person node only.\n  - Do NOT put the LLM/model in `Created by`.\n  - If a `Generated by` field exists on the node type, use that field for `Claude` / `Gemini` / `Human` / `Mixed`.\n- ALWAYS apply project/study as VISIBLE SUPERTAGS using proper supertag DEFINITIONS (created via create_tag)\n  - Project tag is PRIMARY (always apply): e.g. #CLAS RuBase (8kRj7CI8rv4H)\n  - Study tag is SECONDARY (only if item is study-specific): e.g. #Transparent Battlefield (QD176nBX1YuQ)\n  - e.g. project-level: \"Fix scrapers #task #CLAS RuBase\"\n  - e.g. study-specific: \"Seed TB research questions #task #CLAS RuBase #Transparent Battlefield\"\n  - NEVER use node instances as tags (they don't render as visible chips in Tana UI)\n- NEVER rely on import_tana_paste for multi-word tag names (e.g. `#CLAS RuBase` gets split into `#CLAS`). Always use the `tag` tool with explicit tag IDs AFTER importing.\n- ALWAYS add author suffix to node names: `[SDS]`, `[HP]`, `[LH]` etc. at the END of the name\n  - Default: [SDS] for all posts by Claude Code (on behalf of Stephan)\n  - Initials: SDS=Stephan De Spiegeleire, HP=Hryhorii Pavlenko, LH=Liliia Hudziuk\n- ALWAYS set \"Created by\" field after posting: use set_field_content with attributeId per tag type and content = person node ID\n  - Default author: SDS (X6yCff_d87Wn) unless posting on behalf of someone else\n  - Task field: MCkSxKHFv7st | Discussion field: RxLacB6oylwm | Annotation-run field: sxwe-F6paDNj | Meeting field: WPVL2EKgjYjz | Output field: iVa6Q--Yx6q4\n- `Created by` is for the human author/person only, never the LLM/model.\n- Replies use `Author` instead of `Created by`.\n- If the node type has a `Generated by` field, use that field for provenance such as `Claude`, `Gemini`, `Human`, or `Mixed`.\n- For NEW tasks: use HCSS #task (X_vT1GSytHJy) with fields Status/Assignee/Due date/Deliverable/Rizzoma topic\n- Legacy items from Tana Paste imports have main workspace #task (BE4sP3grlp6R) - don't change these\n- Also set the Study field (es7J4At7t9qg on legacy #task, VBdsrqPcgXHS on #discussion) for search/filtering\n- Mark tasks with checkboxes: [ ] for open, [x] for done\n- Set Status field on tasks (To-Do, Doing, Done)\n- ONE daily note entry per logical batch of work, not separate sub-steps\n- The dashboard searches surface items automatically based on tags + field references\n- REPLIES to discussions: add child node with #reply tag, set Author field (person ID) and \"In reply to\" field (context text)\n  - Pattern: import_tana_paste child → tag with #reply → set_field_content for Author + In reply to\n",
            "## Daily Notes Pattern\n- ALWAYS post work to today's daily note (get_or_create_calendar_node, workspace HCSS, granularity: day)\n- Each item is a top-level child of the day node (NOT nested inside a wrapper)\n- Tag every item: #task for actions, #discussion for conversations/notes, #meeting for meetings\n- Provenance rule:\n  - `Created by` is for the HUMAN person node only.\n  - Do NOT put the LLM/model in `Created by`.\n  - Daily-note `#task`, `#discussion`, `#meeting`, and `#output` should ALSO set `Generated by`.\n  - Replies use `Author` for the human person and have no `Generated by` field yet.\n- ALWAYS apply project/study as VISIBLE SUPERTAGS using proper supertag DEFINITIONS (created via create_tag)\n  - Project tag is PRIMARY (always apply): e.g. #CLAS RuBase (8kRj7CI8rv4H)\n  - Study tag is SECONDARY (only if item is study-specific): e.g. #Transparent Battlefield (QD176nBX1YuQ)\n  - e.g. project-level: \"Fix scrapers #task #CLAS RuBase\"\n  - e.g. study-specific: \"Seed TB research questions #task #CLAS RuBase #Transparent Battlefield\"\n  - NEVER use node instances as tags (they don't render as visible chips in Tana UI)\n- NEVER rely on import_tana_paste for multi-word tag names (e.g. `#CLAS RuBase` gets split into `#CLAS`). Always use the `tag` tool with explicit tag IDs AFTER importing.\n- ALWAYS add author suffix to node names: `[SDS]`, `[HP]`, `[LH]` etc. at the END of the name\n  - Default: [SDS] for all posts by Claude Code (on behalf of Stephan)\n  - Initials: SDS=Stephan De Spiegeleire, HP=Hryhorii Pavlenko, LH=Liliia Hudziuk\n- ALWAYS set the human provenance field after posting: use set_field_content with the person node ID\n  - Default author: SDS (X6yCff_d87Wn) unless posting on behalf of someone else\n  - Task: MCkSxKHFv7st | Discussion: RxLacB6oylwm | Annotation-run: sxwe-F6paDNj | Meeting: WPVL2EKgjYjz | Output: iVa6Q--Yx6q4 | Reply Author: Knni2KFxspb6\n- `Created by` is for the human author/person only, never the LLM/model.\n- Daily-note `#task`, `#discussion`, `#meeting`, and `#output` should ALSO set `Generated by`.\n  - Task: dG5OQzKA6eYV | Discussion: BaewUwERUcWs | Meeting: DL0Fe4k1v_bQ | Output: MUJwRwDzb2pW\n- Replies use `Author` instead of `Created by` and currently have no `Generated by` field.\n- `#annotation-run` currently uses only `Created by` unless a `Generated by` field is added later.\n- For NEW tasks: use HCSS #task (X_vT1GSytHJy) with fields Status/Assignee/Due date/Deliverable/Rizzoma topic\n- Legacy items from Tana Paste imports have main workspace #task (BE4sP3grlp6R) - don't change these\n- Also set the Study field (es7J4At7t9qg on legacy #task, VBdsrqPcgXHS on #discussion) for search/filtering\n- Mark tasks with checkboxes: [ ] for open, [x] for done\n- Set Status field on tasks (To-Do, Doing, Done)\n- ONE daily note entry per logical batch of work, not separate sub-steps\n- The dashboard searches surface items automatically based on tags + field references\n- REPLIES to discussions: add child node with #reply tag, set Author field (person ID) and \"In reply to\" field (context text)\n  - Pattern: import_tana_paste child → tag with #reply → set_field_content for Author + In reply to\n",
        ),
    ],
    "/mnt/c/Apps/Tana/docs/tana-claude-workflow.md": [
        (
            "# Tana + Claude Code Workflow Patterns\n\n## Overview\n",
            "# Tana + Claude Code Workflow Patterns\n\n> Local mirror: use `/mnt/g/My Drive/Tana/tana-claude-workflow.md` as canonical when available.\n> This copy should be kept aligned with the canonical file but is secondary.\n\n## Overview\n",
        ),
        (
            "### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Read by: nB79F1NNg4pn (multi, instance #person) | Rizzoma date: 40vNbX5qVJwL\n",
            "### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz | Generated by: DL0Fe4k1v_bQ\n- Generated by opts: Claude(vE1SjO_A6cUG), Codex(ashbc8EMmP8i), Gemini(0Ob6wrWQgIMC), Human(7RTLGhAPoHi7), Mixed(UejRJCmsiM1T)\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Generated by: BaewUwERUcWs | Read by: nB79F1NNg4pn (multi, instance #person) | Rizzoma date: 40vNbX5qVJwL\n- Generated by opts: Claude(I_e177ygtAEE), Codex(Fn38sEgtZmde), Gemini(GRi58kV6LLaZ), Human(1gWeePPtLrJS), Mixed(KtEGVvl8ox62)\n",
        ),
        (
            "### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Read by: nB79F1NNg4pn (multi, instance #person) | Rizzoma date: 40vNbX5qVJwL\n",
            "### Field IDs (meeting)\n- Date: VTJCCR9lOokb | Attendees: cq1AzcRz4AZu | Meeting link: iKSSrormyy1S | Rizzoma date: fJpJo6u6atW9 | Created by: WPVL2EKgjYjz | Generated by: DL0Fe4k1v_bQ\n- Generated by opts: Claude(vE1SjO_A6cUG), Codex(ashbc8EMmP8i), Gemini(0Ob6wrWQgIMC), Human(7RTLGhAPoHi7), Mixed(UejRJCmsiM1T)\n\n### Field IDs (discussion)\n- Study: VBdsrqPcgXHS | Participants: tdP2bfHYH6ud | Rizzoma topic: NJLHIxFaHqO4 | Created by: RxLacB6oylwm | Generated by: BaewUwERUcWs | Read by: nB79F1NNg4pn (multi, instance #person) | Rizzoma date: 40vNbX5qVJwL\n- Generated by opts: Claude(I_e177ygtAEE), Codex(Fn38sEgtZmde), Gemini(GRi58kV6LLaZ), Human(1gWeePPtLrJS), Mixed(KtEGVvl8ox62)\n",
        ),
        (
            "- Created by: MCkSxKHFv7st (instance of #person)\n",
            "- Created by: MCkSxKHFv7st (instance of #person)\n- Generated by: dG5OQzKA6eYV (options: Claude/AUjPowsHSBEC, Codex/S1L6t4Bq8A_Z, Gemini/hCcjwptnMN5v, Human/v0TVDCg8FOeq, Mixed/q4Xdq294wZlw)\n",
        ),
        (
            "- Provenance rule:\n  - `Created by` is for the HUMAN person node only.\n  - Do NOT put the LLM/model in `Created by`.\n  - For replies, use `Author` as the human provenance field.\n  - If a `Generated by` field exists on the node type, use that field for `Claude` / `Gemini` / `Human` / `Mixed`.\n",
            "- Provenance rule:\n  - `Created by` is for the HUMAN person node only.\n  - Do NOT put the LLM/model in `Created by`.\n  - For replies, use `Author` as the human provenance field.\n  - For daily-note `#task`, `#discussion`, `#meeting`, and `#output`, ALSO set `Generated by`.\n",
        ),
        (
            '- ALWAYS set "Created by" field after posting: use set_field_content with attributeId per tag type and content = person node ID\n  - Task: MCkSxKHFv7st | Discussion: RxLacB6oylwm | Annotation-run: sxwe-F6paDNj\n- `Created by` is for the human author/person only, never the LLM/model.\n- Replies use `Author` instead of `Created by`.\n- If the node type has a `Generated by` field, use that field for provenance such as `Claude`, `Gemini`, `Human`, or `Mixed`.\n',
            '- ALWAYS set the human provenance field after posting: use set_field_content with the person node ID\n  - Task: MCkSxKHFv7st | Discussion: RxLacB6oylwm | Annotation-run: sxwe-F6paDNj | Meeting: WPVL2EKgjYjz | Output: iVa6Q--Yx6q4 | Reply Author: Knni2KFxspb6\n- `Created by` is for the human author/person only, never the LLM/model.\n- Daily-note `#task`, `#discussion`, `#meeting`, and `#output` should ALSO set `Generated by`.\n  - Task: dG5OQzKA6eYV | Discussion: BaewUwERUcWs | Meeting: DL0Fe4k1v_bQ | Output: MUJwRwDzb2pW\n- Replies use `Author` instead of `Created by` and currently have no `Generated by` field.\n- `#annotation-run` currently uses only `Created by` unless a `Generated by` field is added later.\n',
        ),
    ],
}


def main():
    for path_str, replacements in REPLACEMENTS.items():
        path = pathlib.Path(path_str)
        text = path.read_text()
        original = text
        for old, new in replacements:
            if old in text:
                text = text.replace(old, new)
                continue
            if new in text:
                continue
            raise RuntimeError(f"Expected snippet not found in {path}")
        if text != original:
            path.write_text(text)
            print(f"updated {path}")
        else:
            print(f"unchanged {path}")


if __name__ == "__main__":
    main()
